-- MySQL Script generated by MySQL Workbench
-- 01/23/17 21:53:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `lineas_investigacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lineas_investigacion` ;

CREATE TABLE IF NOT EXISTS `lineas_investigacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clasificaciones_grupos_investigacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clasificaciones_grupos_investigacion` ;

CREATE TABLE IF NOT EXISTS `clasificaciones_grupos_investigacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gran_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gran_areas` ;

CREATE TABLE IF NOT EXISTS `gran_areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `areas` ;

CREATE TABLE IF NOT EXISTS `areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_gran_area` INT NOT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `created_at` DATE NULL,
  `deleted_at` DATE NULL,
  `updated_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_areas_gran_areas_idx` (`id_gran_area` ASC),
  CONSTRAINT `fk_areas_gran_areas`
    FOREIGN KEY (`id_gran_area`)
    REFERENCES `gran_areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sedes_ucc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sedes_ucc` ;

CREATE TABLE IF NOT EXISTS `sedes_ucc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `ciudad` VARCHAR(250) NULL,
  `departamento_estado` VARCHAR(250) NULL,
  `pais` VARCHAR(250) NULL,
  `descripcion` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facultades_dependencias_ucc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `facultades_dependencias_ucc` ;

CREATE TABLE IF NOT EXISTS `facultades_dependencias_ucc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_sede_ucc` INT NOT NULL,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facultades_dependencias_sedes1_idx` (`id_sede_ucc` ASC),
  CONSTRAINT `fk_facultades_dependencias_sedes1`
    FOREIGN KEY (`id_sede_ucc`)
    REFERENCES `sedes_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupos_investigacion_ucc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupos_investigacion_ucc` ;

CREATE TABLE IF NOT EXISTS `grupos_investigacion_ucc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_facultad_dependencia_ucc` INT NOT NULL,
  `id_area` INT NULL,
  `id_clasificacion_grupo_investigacion` INT NULL,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupos_investigacion_clasificaciones_grupos_investigacio_idx` (`id_clasificacion_grupo_investigacion` ASC),
  INDEX `fk_grupos_investigacion_areas1_idx` (`id_area` ASC),
  INDEX `fk_grupos_investigacion_facultades_dependencias1_idx` (`id_facultad_dependencia_ucc` ASC),
  CONSTRAINT `fk_grupos_investigacion_clasificaciones_grupos_investigacion1`
    FOREIGN KEY (`id_clasificacion_grupo_investigacion`)
    REFERENCES `clasificaciones_grupos_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_investigacion_areas1`
    FOREIGN KEY (`id_area`)
    REFERENCES `areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_investigacion_facultades_dependencias1`
    FOREIGN KEY (`id_facultad_dependencia_ucc`)
    REFERENCES `facultades_dependencias_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estados` ;

CREATE TABLE IF NOT EXISTS `estados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorias_investigadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias_investigadores` ;

CREATE TABLE IF NOT EXISTS `categorias_investigadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_identificacion` ;

CREATE TABLE IF NOT EXISTS `tipos_identificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `acronimo` VARCHAR(45) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personas` ;

CREATE TABLE IF NOT EXISTS `personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_categoria_investigador` INT NULL,
  `id_tipo_identificacion` INT NULL,
  `nombres` VARCHAR(250) NULL,
  `apellidos` VARCHAR(500) NULL,
  `edad` INT NULL,
  `sexo` VARCHAR(45) NULL,
  `identificacion` INT NULL,
  `formacion` VARCHAR(250) NULL,
  `foto` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personas_categorias_investigadores1_idx` (`id_categoria_investigador` ASC),
  INDEX `fk_personas_tipos_indetificacion1_idx` (`id_tipo_identificacion` ASC),
  CONSTRAINT `fk_personas_categorias_investigadores1`
    FOREIGN KEY (`id_categoria_investigador`)
    REFERENCES `categorias_investigadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_tipos_indetificacion1`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `tipos_identificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enlaces_redes_sociales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enlaces_redes_sociales` ;

CREATE TABLE IF NOT EXISTS `enlaces_redes_sociales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enlaces_redes_sociales_personas1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_enlaces_redes_sociales_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `id_grupo_investigacion_ucc` INT NULL,
  `username` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  `remember_token` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_estados1_idx` (`id_estado` ASC),
  INDEX `fk_usuarios_roles1_idx` (`id_rol` ASC),
  INDEX `fk_usuarios_personas1_idx` (`id_persona` ASC),
  INDEX `fk_usuarios_grupos_investigacion1_idx` (`id_grupo_investigacion_ucc` ASC),
  CONSTRAINT `fk_usuarios_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_grupos_investigacion1`
    FOREIGN KEY (`id_grupo_investigacion_ucc`)
    REFERENCES `grupos_investigacion_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectos` ;

CREATE TABLE IF NOT EXISTS `proyectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_grupo_investigacion_ucc` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `codigo_fmi` VARCHAR(250) NULL,
  `subcentro_costo` VARCHAR(250) NULL,
  `nombre` VARCHAR(250) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `duracion_meses` INT NULL,
  `convocatoria` VARCHAR(250) NULL,
  `anio_convocatoria` VARCHAR(100) NULL,
  `objetivo_general` VARCHAR(500) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyectos_estados1_idx` (`id_estado` ASC),
  INDEX `fk_proyectos_grupos_investigacion1_idx` (`id_grupo_investigacion_ucc` ASC),
  CONSTRAINT `fk_proyectos_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_grupos_investigacion1`
    FOREIGN KEY (`id_grupo_investigacion_ucc`)
    REFERENCES `grupos_investigacion_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `investigadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `investigadores` ;

CREATE TABLE IF NOT EXISTS `investigadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_investigador_principal` INT NULL,
  `id_persona_coinvestigador` INT NULL,
  `id_grupo_investigacion_ucc` INT NULL,
  `id_rol` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  `entidad_o_grupo_investigacion` VARCHAR(250) NULL,
  `programa_academico` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `dedicacion_horas_semanales` INT NULL,
  `total_semanas` INT NULL,
  `valor_hora` DECIMAL NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_investigadores_usuarios1_idx` (`id_usuario_investigador_principal` ASC),
  INDEX `fk_investigadores_proyectos1_idx` (`id_proyecto` ASC),
  INDEX `fk_investigadores_personas1_idx` (`id_persona_coinvestigador` ASC),
  INDEX `fk_investigadores_grupos_investigacion_ucc1_idx` (`id_grupo_investigacion_ucc` ASC),
  INDEX `fk_investigadores_roles1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_investigadores_usuarios1`
    FOREIGN KEY (`id_usuario_investigador_principal`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigadores_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigadores_personas1`
    FOREIGN KEY (`id_persona_coinvestigador`)
    REFERENCES `personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigadores_grupos_investigacion_ucc1`
    FOREIGN KEY (`id_grupo_investigacion_ucc`)
    REFERENCES `grupos_investigacion_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigadores_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formatos_tipos_documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formatos_tipos_documentos` ;

CREATE TABLE IF NOT EXISTS `formatos_tipos_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `archivo` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documentos_proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documentos_proyectos` ;

CREATE TABLE IF NOT EXISTS `documentos_proyectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL,
  `id_formato_tipo_documento` INT NOT NULL,
  `archivo` VARCHAR(500) NULL,
  `aprobado` TINYINT(1) NULL DEFAULT 0,
  `comentario_investigador` VARCHAR(250) NULL,
  `comentario_revision` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_documentos_proyectos_tipos_documentos_proyectos1_idx` (`id_formato_tipo_documento` ASC),
  INDEX `fk_documentos_proyectos_proyectos1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_documentos_proyectos_tipos_documentos_proyectos1`
    FOREIGN KEY (`id_formato_tipo_documento`)
    REFERENCES `formatos_tipos_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_proyectos_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objetivos_especificos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `objetivos_especificos` ;

CREATE TABLE IF NOT EXISTS `objetivos_especificos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `nombre` VARCHAR(500) NOT NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objetivos_especificos_proyectos1_idx` (`id_proyecto` ASC),
  INDEX `fk_objetivos_especificos_estados1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_objetivos_especificos_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objetivos_especificos_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entidades_fuente_presupuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entidades_fuente_presupuesto` ;

CREATE TABLE IF NOT EXISTS `entidades_fuente_presupuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_gastos` ;

CREATE TABLE IF NOT EXISTS `tipos_gastos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalles_gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalles_gastos` ;

CREATE TABLE IF NOT EXISTS `detalles_gastos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_gasto` INT NOT NULL,
  `id_investigador` INT NULL,
  `fecha_ejecucion` DATE NOT NULL,
  `concepto` VARCHAR(250) NULL,
  `justificacion` VARCHAR(250) NULL,
  `numero_salidas` INT NULL,
  `valor_unitario` DECIMAL NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalles_gastos_presupuesto_tipo_detalles_gastos_presupu_idx` (`id_tipo_gasto` ASC),
  INDEX `fk_detalles_gastos_presupuesto_investigadores1_idx` (`id_investigador` ASC),
  CONSTRAINT `fk_detalles_gastos_presupuesto_tipo_detalles_gastos_presupues1`
    FOREIGN KEY (`id_tipo_gasto`)
    REFERENCES `tipos_gastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_gastos_presupuesto_investigadores1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `investigadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gastos` ;

CREATE TABLE IF NOT EXISTS `gastos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL,
  `id_entidad_fuente_presupuesto` INT NOT NULL,
  `id_detalle_gasto` INT NOT NULL,
  `valor` DECIMAL NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fuentes_presupuesto_entidades_fuente_presupuesto1_idx` (`id_entidad_fuente_presupuesto` ASC),
  INDEX `fk_fuentes_presupuesto_proyectos1_idx` (`id_proyecto` ASC),
  INDEX `fk_gastos_detalles_gastos1_idx` (`id_detalle_gasto` ASC),
  CONSTRAINT `fk_fuentes_presupuesto_entidades_fuente_presupuesto1`
    FOREIGN KEY (`id_entidad_fuente_presupuesto`)
    REFERENCES `entidades_fuente_presupuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fuentes_presupuesto_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_detalles_gastos1`
    FOREIGN KEY (`id_detalle_gasto`)
    REFERENCES `detalles_gastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desembolsos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desembolsos` ;

CREATE TABLE IF NOT EXISTS `desembolsos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_detalle_gasto` INT NOT NULL,
  `id_formato_tipo_documento` INT NOT NULL,
  `archivo` VARCHAR(500) NULL,
  `aprobado` TINYINT(1) NULL DEFAULT 0,
  `codigo_aprobacion` VARCHAR(250) NULL,
  `comentario_investigador` VARCHAR(250) NULL,
  `comentario_revision` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_desembolsos_detalle_gasto_presupuesto1_idx` (`id_detalle_gasto` ASC),
  INDEX `fk_desembolsos_formatos_tipos_documentos1_idx` (`id_formato_tipo_documento` ASC),
  CONSTRAINT `fk_desembolsos_detalle_gasto_presupuesto1`
    FOREIGN KEY (`id_detalle_gasto`)
    REFERENCES `detalles_gastos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desembolsos_formatos_tipos_documentos1`
    FOREIGN KEY (`id_formato_tipo_documento`)
    REFERENCES `formatos_tipos_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_productos_generales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_productos_generales` ;

CREATE TABLE IF NOT EXISTS `tipos_productos_generales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_productos_especificos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_productos_especificos` ;

CREATE TABLE IF NOT EXISTS `tipos_productos_especificos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_producto_general` INT NOT NULL,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipos_especificos_tipos_generales1_idx` (`id_tipo_producto_general` ASC),
  CONSTRAINT `fk_tipos_especificos_tipos_generales1`
    FOREIGN KEY (`id_tipo_producto_general`)
    REFERENCES `tipos_productos_generales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

CREATE TABLE IF NOT EXISTS `productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT NOT NULL,
  `id_tipo_producto_especifico` INT NOT NULL,
  `id_investigador` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `nombre` VARCHAR(500) NULL,
  `fecha_proyectada_radicacion` DATE NULL,
  `fecha_remision` DATE NULL,
  `fecha_confirmacion_editorial` DATE NULL,
  `fecha_recepcion_evaluacion` DATE NULL,
  `fecha_respuesta_evaluacion` DATE NULL,
  `fecha_aprobacion_publicacion` DATE NULL,
  `fecha_publicacion` DATE NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_tipos_especificos1_idx` (`id_tipo_producto_especifico` ASC),
  INDEX `fk_productos_proyectos1_idx` (`id_proyecto` ASC),
  INDEX `fk_productos_estados1_idx` (`id_estado` ASC),
  INDEX `fk_productos_investigadores1_idx` (`id_investigador` ASC),
  CONSTRAINT `fk_productos_tipos_especificos1`
    FOREIGN KEY (`id_tipo_producto_especifico`)
    REFERENCES `tipos_productos_especificos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `proyectos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_investigadores1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `investigadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipos_postulaciones_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_postulaciones_publicaciones` ;

CREATE TABLE IF NOT EXISTS `tipos_postulaciones_publicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `postulaciones_publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `postulaciones_publicaciones` ;

CREATE TABLE IF NOT EXISTS `postulaciones_publicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_tipo_postulacion_publicacion` INT NOT NULL,
  `archivo` VARCHAR(250) NULL,
  `descripcion` VARCHAR(250) NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postulaciones_tipos_postulaciones1_idx` (`id_tipo_postulacion_publicacion` ASC),
  INDEX `fk_postulaciones_productos1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_postulaciones_tipos_postulaciones1`
    FOREIGN KEY (`id_tipo_postulacion_publicacion`)
    REFERENCES `tipos_postulaciones_publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postulaciones_productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lineas_grupos_investigacion_ucc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lineas_grupos_investigacion_ucc` ;

CREATE TABLE IF NOT EXISTS `lineas_grupos_investigacion_ucc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_grupo_investigacion_ucc` INT NOT NULL,
  `id_linea_investigacion` INT NOT NULL,
  `created_at` DATE NULL,
  `updated_at` DATE NULL,
  `deleted_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lineas_grupos_investigacion_grupos_investigacion1_idx` (`id_grupo_investigacion_ucc` ASC),
  INDEX `fk_lineas_grupos_investigacion_lineas_investigacion1_idx` (`id_linea_investigacion` ASC),
  CONSTRAINT `fk_lineas_grupos_investigacion_grupos_investigacion1`
    FOREIGN KEY (`id_grupo_investigacion_ucc`)
    REFERENCES `grupos_investigacion_ucc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lineas_grupos_investigacion_lineas_investigacion1`
    FOREIGN KEY (`id_linea_investigacion`)
    REFERENCES `lineas_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `password_reminders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `password_reminders` ;

CREATE TABLE IF NOT EXISTS `password_reminders` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL,
  `created_at` DATE NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `migrations` ;

CREATE TABLE IF NOT EXISTS `migrations` (
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  `created_at` DATE NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
